# This workflow will run python tests after setup

name: Python application

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - run: echo "Hello World!"
